language: generic 
# run docker
sudo: required
services:
  - docker
# build Dockfile.dev
before_install:
  - docker build -t gundalf72/docker-react -f Dockerfile.dev .
# tell it how to run tests
script:
  - docker run -e CI=true gundalf72/docker-react npm run test -- --coverage

# deploy to AWS
deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-518491185730"
  bucket_path: "docker-react"
  on:
    branch: master