language: generic 
# run docker
sudo: required
services:
  - docker
# build Dockfile.dev
before_install:
  - docker build -t Gundalf72/docker-react -f Dockerfile.dev .
# tell it how to run tests
script:
  - docker run -e CI=true Gundalf72/docker-react npm run test -- --coverage

# deploy to AWS
